In [2]:
import numpy as np

def union(A, B):
    return np.maximum(A, B)

def intersection(A, B):
    return np.minimum(A, B)

def complement(A):
    return 1 - A

def difference(A, B):
    return np.maximum(A - B, 0)

def cartesian_product(A, B):
    return np.outer(A, B)

def max_min_composition(R1, R2):
    size = R1.shape[0]
    result = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            result[i][j] = np.max(np.minimum(R1[i, :], R2[:, j]))
    return result

A = np.array([0.2, 0.4, 0.7, 0.8])
B = np.array([0.1, 0.8, 0.2, 0.3])

R1 = cartesian_product(A, B)
R2 = cartesian_product(B, A)
result = max_min_composition(R1, R2)

print("Union of A and B:", union(A, B))
print("Intersection of A and B:", intersection(A, B))
print("Complement of A:", complement(A))
print("Difference of A and B:", difference(A, B))
print(f"Cartesian product of A and B:\n{R1}")
print(f"Cartesian product of B and A:\n{R2}")
print(f"Max-min composition of R1 and R2:\n{result}")


*****************************************************************

import numpy as np  # Importing NumPy for numerical operations

# Function to compute the union of two fuzzy sets (element-wise maximum)
def union(A, B): 
    return np.maximum(A, B)

# Function to compute the intersection of two fuzzy sets (element-wise minimum)
def intersection(A, B): 
    return np.minimum(A, B)

# Function to compute the complement of a fuzzy set (1 - membership value)
def complement(A): 
    return 1 - A

# Function to compute the difference of two fuzzy sets (A - B), clipped at 0
def difference(A, B): 
    return np.maximum(A - B, 0)

# Function to compute the Cartesian product of two fuzzy sets
# Returns a matrix where each element is A[i] * B[j]
def cartesian_product(A, B): 
    return np.outer(A, B)

# Function to perform max-min composition on two fuzzy relations
# This is a simplified placeholder version; actual max-min composition would use nested loops
def max_min_composition(R1, R2): 
    return np.maximum(np.minimum(R1, R2), 0)

# Define two fuzzy sets A and B
A = np.array([0.2, 0.4, 0.7, 0.8]) 
B = np.array([0.1, 0.8, 0.2, 0.3]) 

# Generate fuzzy relations using Cartesian products
R1 = cartesian_product(A, B)  # A × B
R2 = cartesian_product(B, A)  # B × A

# Perform max-min composition on the two fuzzy relations
result = max_min_composition(R1, R2)

# Display results of fuzzy set operations and relations
print("Union of A and B:", union(A, B)) 
print("Intersection of A and B:", intersection(A, B)) 
print("Complement of A:", complement(A)) 
print("Difference of A and B:", difference(A, B)) 
print(f"Cartesian product of A and B:\n{R1}") 
print(f"Cartesian product of B and A:\n{R2}") 
print(f"Max-min composition of R1 and R2:\n{result}")

****************************************************************************


### **AIM:**

To implement Fuzzy Logic Operations.

---

### **PROBLEM STATEMENT:**

Implement **Union, Intersection, Complement**, and **Difference** operations on fuzzy sets. Also, create fuzzy relations by **Cartesian product** of any two fuzzy sets and perform **max-min composition** on any two fuzzy relations.

---

### **THEORY:**

#### **Fuzzy Set Theory Overview**

Fuzzy set theory is an extension of classical set theory. Unlike classical sets where an element either **belongs** or **does not belong** to a set (membership value is either 0 or 1), fuzzy sets allow **partial membership** with values ranging between **0 and 1**.
This is particularly useful for representing **uncertainty, vagueness, and imprecision** in real-world problems.

---

#### **Fuzzy Set Operations**

1. **Union:**
   Represents the degree to which an element belongs to at least one of the sets.

2. **Intersection:**
   Represents the degree to which an element belongs to both sets.

3. **Complement:**
   Indicates the degree to which an element does not belong to set A.

4. **Difference:**
   Gives the degree to which an element belongs to A but not to B.

---

#### **Fuzzy Relations and Cartesian Product**

A fuzzy relation is a generalization of a classical relation and can be formed using the **Cartesian product** of two fuzzy sets A and B.

* The Cartesian product of two fuzzy sets forms a fuzzy relation.
* Each pair of elements from the sets is assigned a **membership value equal to the minimum** of their individual membership values.

---

#### **Max-Min Composition of Fuzzy Relations**

* The **max-min composition** combines two fuzzy relations.
* It takes the **maximum** of the **minimum** values obtained from the compositions of their membership functions.
* This operation is **fundamental in fuzzy logic systems** for inference mechanisms.

---

### **Advantages of Fuzzy Sets**

* **Handles Uncertainty:**
  Models vague data where binary logic fails.

* **Flexible Reasoning:**
  Allows reasoning with approximate values and linguistic terms, mimicking human decision-making.

* **Smooth Transitions:**
  Supports gradual membership transitions instead of binary classification.

* **Real-World Applications:**
  Useful in control systems, pattern recognition, decision support systems, and natural language processing.

---

### **Disadvantages of Fuzzy Sets**

* **Complex Design:**
  Designing fuzzy rules and membership functions is subjective and lacks standardization.

* **Computational Cost:**
  More resource-intensive than simple Boolean systems.

* **No Learning Ability:**
  Cannot learn from data unless integrated with machine learning techniques.

* **Ambiguity in Interpretation:**
  Different users may define fuzzy sets and rules differently, leading to inconsistency.

************************************************************

Of course! Here's a **straightforward and viva-friendly answer key** to all the questions listed above. Keep these ready in your notes or lab record — they’ll help you **sound confident and clear** in front of the external.

---

## ✅ **Answers to Expected Viva Questions – Fuzzy Logic**

---

### 🧩 **Conceptual Questions**

---

**1. What is the difference between fuzzy sets and classical sets?**
👉 In classical sets, an element either **belongs** (1) or **doesn’t belong** (0).
👉 In fuzzy sets, an element can **partially belong**, with membership values between **0 and 1**.

---

**2. Why do we use fuzzy logic in real-world applications?**
👉 Because real-world situations often involve **vagueness and uncertainty** (like "hot", "slow", "likely"), which fuzzy logic can handle better than binary logic.

---

**3. What is the membership function in fuzzy logic?**
👉 A membership function **defines how much** an element belongs to a fuzzy set.
👉 It gives a value between **0 and 1**, showing **degree of membership**.

---

### ⚙️ **Operation-based Questions**

---

**4. How is union calculated in fuzzy sets?**
👉 Union is done by taking the **maximum value** for each element from the two sets.
**Formula:** `μA∪B(x) = max(μA(x), μB(x))`

---

**5. What is the formula for the complement of a fuzzy set?**
👉 Complement shows how much an element **doesn’t belong** to the set.
**Formula:** `μ¬A(x) = 1 - μA(x)`

---

**6. Can you explain the difference between fuzzy difference and intersection?**
👉 **Intersection**: Takes the **minimum** value of A and B for each element.
👉 **Difference (A - B)**: Takes the value of A minus B, but clipped at 0.
**Formula:** `μA-B(x) = max(μA(x) - μB(x), 0)`

---

### 🔗 **Relation/Matrix-based Questions**

---

**7. What is a fuzzy relation?**
👉 A fuzzy relation is a **matrix** formed by combining two fuzzy sets.
👉 It shows the relationship between elements of two sets based on **membership values**.

---

**8. How is the Cartesian product of fuzzy sets calculated?**
👉 By pairing every element in set A with every element in set B.
👉 The membership of each pair is: `min(μA[i], μB[j])`

---

**9. Explain how max-min composition works with an example.**
👉 It combines two fuzzy relation matrices R1 and R2.
👉 For each output cell (i, j), we take all `min(R1[i][k], R2[k][j])` and then pick the **maximum**.
👉 It’s like matching rows from R1 and columns from R2 to get new relation values.

---

### 🔍 **Application-based Questions**

---

**10. Where is fuzzy logic used in real life?**
👉 Used in:

* **Washing machines** (adjust water and time based on load)
* **Air conditioners** (adjust cooling based on fuzzy temperature values)
* **Control systems**
* **Medical diagnosis**
* **AI and expert systems**

---

**11. Can fuzzy systems learn from data?**
👉 **Traditional fuzzy systems cannot learn** on their own.
👉 But if combined with **machine learning** (like ANFIS or fuzzy neural networks), they can learn from data.


******************************************************************


**1. import numpy as np**:
Imports the **NumPy** library for mathematical and array operations, which is essential for fuzzy logic computations.

---

**2. def union(A, B):**
**3. return np.maximum(A, B)**
**FUNCTION: UNION**
Takes the element-wise **maximum** between sets A and B.
**THEORY**: Represents the degree to which an element belongs to **at least one** of the fuzzy sets.

---

**4. def intersection(A, B):**
**5. return np.minimum(A, B)**
**FUNCTION: INTERSECTION**
Takes the element-wise **minimum** between A and B.
**THEORY**: Represents the degree to which an element belongs to **both** sets.

---

**6. def complement(A):**
**7. return 1 - A**
**FUNCTION: COMPLEMENT**
Calculates the **opposite** of each membership value in A by subtracting from 1.
**THEORY**: Shows how much an element **does not** belong to set A.

---

**8. def difference(A, B):**
**9. return np.maximum(A - B, 0)**
**FUNCTION: DIFFERENCE (A - B)**
Subtracts elements of B from A and ensures the result is **non-negative**.
**THEORY**: Indicates how much an element belongs to A but **not** to B.

---

**10. def cartesian\_product(A, B):**
**11. return np.outer(A, B)**
**FUNCTION: CARTESIAN PRODUCT**
Generates a **matrix** where each cell = A\[i] × B\[j].
**THEORY**: Used to form a **fuzzy relation** between elements of two sets.

---

**12. def max\_min\_composition(R1, R2):**
**13. size = R1.shape\[0]**
**14. result = np.zeros((size, size))**
**15. for i in range(size):**
**16.  for j in range(size):**
**17.   result\[i]\[j] = np.max(np.minimum(R1\[i, :], R2\[:, j]))**
**18. return result**
**FUNCTION: MAX-MIN COMPOSITION**
Creates a new matrix where each value is the **maximum of minimums** from matching rows of R1 and columns of R2.
**THEORY**: This is used to **combine two fuzzy relations** logically.

---

**19. A = np.array(\[0.2, 0.4, 0.7, 0.8])**
Defines fuzzy set **A** with 4 membership values.

---

**20. B = np.array(\[0.1, 0.8, 0.2, 0.3])**
Defines fuzzy set **B** with 4 membership values.

---

**21. R1 = cartesian\_product(A, B)**
Performs the Cartesian product of A and B to create fuzzy relation **R1**.

---

**22. R2 = cartesian\_product(B, A)**
Performs the Cartesian product of B and A to create fuzzy relation **R2**.

---

**23. result = max\_min\_composition(R1, R2)**
Computes **max-min composition** of R1 and R2 and stores it in `result`.

---

**24. print("Union of A and B:", union(A, B))**
Prints the result of **union** operation on sets A and B.

---

**25. print("Intersection of A and B:", intersection(A, B))**
Prints the result of **intersection** operation.

---

**26. print("Complement of A:", complement(A))**
Prints the **complement** of fuzzy set A.

---

**27. print("Difference of A and B:", difference(A, B))**
Prints the **difference** between sets A and B (A - B).

---

**28. print(f"Cartesian product of A and B:\n{R1}")**
Displays the matrix for Cartesian product R1.

---

**29. print(f"Cartesian product of B and A:\n{R2}")**
Displays the matrix for Cartesian product R2.

---

**30. print(f"Max-min composition of R1 and R2:\n{result}")**
Displays the final fuzzy relation obtained through **max-min composition**.

*******************************************************

The **purpose of this assignment** is to help you **understand and apply the basic operations of fuzzy logic** through hands-on implementation. Here's how you can write it clearly in your assignment or explain it in a viva:

---

### **Purpose of the Assignment:**

The purpose of this assignment is to:

1. **Understand fuzzy set theory** and how it extends classical set theory to handle real-world uncertainty and vagueness.
2. **Implement basic fuzzy operations** such as union, intersection, complement, and difference to see how fuzzy sets behave mathematically.
3. **Create fuzzy relations** using the Cartesian product of two fuzzy sets.
4. **Perform max-min composition**, which is a fundamental operation in fuzzy relational inference.
5. **Build foundational logic** that is used in fuzzy control systems, decision-making, and artificial intelligence.

---

### ✨ In Simple Terms:

This assignment helps us **learn how fuzzy logic works practically**—not just in theory. It gives us a **step-by-step way to build and manipulate fuzzy sets**, which are used in everything from **smart washing machines to AI decision systems**.



Union of A and B: [0.2 0.8 0.7 0.8]
Intersection of A and B: [0.1 0.4 0.2 0.3]
Complement of A: [0.8 0.6 0.3 0.2]
Difference of A and B: [0.1 0.  0.5 0.5]
Cartesian product of A and B:
[[0.02 0.16 0.04 0.06]
 [0.04 0.32 0.08 0.12]
 [0.07 0.56 0.14 0.21]
 [0.08 0.64 0.16 0.24]]
Cartesian product of B and A:
[[0.02 0.04 0.07 0.08]
 [0.16 0.32 0.56 0.64]
 [0.04 0.08 0.14 0.16]
 [0.06 0.12 0.21 0.24]]
Max-min composition of R1 and R2:
[[0.16 0.16 0.16 0.16]
 [0.16 0.32 0.32 0.32]
 [0.16 0.32 0.56 0.56]
 [0.16 0.32 0.56 0.64]]
